README.md

Fix the URL for reporting coverage status, and the pip install statement to use the newest package name

Repo Name Change Fixes

---

src/cbc_sdk/base.py

CBAPI-1765
Remove `yield` after `return` as that is unreachable code
Codeship passes

Remove unreachable code

---

examples/platform/list_devices.py
src/cbc_sdk/base.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/rest_api.py
src/tests/unit/audit_remediation/test_rest_api.py
src/tests/unit/platform/test_platform_devices.py

https://jira.carbonblack.local/browse/CBAPI-1508
Asynchronous query support added to CBC SDK:
* Support for asynchronous executor object in CBCloudAPI
* New AsyncQueryMixin to be added to query objects for asynchronous query support
* Mixin added to DeviceSearchQuery and support added
* list_devices.py example updated to optionally use async query (execute_async() method) via --asynchronous or -Y command line flag
Unit tests have been added for specific functionality. In addition, list_devices.py has been run both with and without the asynchronous option and the outputs have been verified to be equivalent.

CBAPI-1508: Add Asynchronous Query Support and Demonstration on DeviceSearchQuery

---

examples/enterprise_edr/threat_intelligence/README.md
src/tests/unit/platform/test_alertsv6_api.py

Added a missing character and descriptive code comments to the threat intelligence module's MISP example

Fix MISP example for Threat Intel module

---

README.md
docs/getting-started.rst

https://jira.carbonblack.local/browse/CBAPI-2076
Add a small section to the Getting Started guide about setting your User-Agent, and to the README
Build the documentation from the top-level directory:
```
sphinx-apidoc -f -o docs src/cbc_sdk
cd docs
make html
```
Then view the file `docs/_build/html/getting-started.html`

CBAPI-2076 User-Agent

---

src/cbc_sdk/enterprise_edr/base.py
src/tests/unit/enterprise_edr/test_enterprise_edr_events.py
src/tests/unit/enterprise_edr/test_enterprise_edr_query.py
src/tests/unit/fixtures/enterprise_edr/mock_events.py
src/tests/unit/fixtures/enterprise_edr/mock_process.py

https://jira.carbonblack.local/browse/CBAPI-2058
Add the asynchronous query functionality (execute_async()) to AsyncProcessQuery (the query for the Process object) and Query (the query for the Event object).
New unit tests have been added to show that the asynchronous queries performs in the same manner as the synchronous queries.

CBAPI-2058: add asynchronous query support to process and process event queries

---

examples/enterprise_edr/device_processes.py

https://jira.carbonblack.local/browse/CBAPI-2019
Added an example script to show multiple process searches running asynchronously, one for each device.
Script has been run against prod02.

CBAPI-2019: added device processes example script

---

src/cbc_sdk/enterprise_edr/base.py
src/tests/unit/enterprise_edr/test_enterprise_edr_events.py
src/tests/unit/fixtures/enterprise_edr/mock_events.py

CBAPI-2147
Fix off by one error
All unit tests pass and new unit test added

Fix off by one error

---

examples/endpoint_standard/live_response_cli.py
src/cbc_sdk/base.py
src/cbc_sdk/endpoint_standard/base.py
src/cbc_sdk/rest_api.py

https://jira.carbonblack.local/browse/CBAPI-2180
Converted the docstrings that were still in the older format (mainly in code ported over from CBAPI) to Google format.
All unit tests run successfully with these changes. No new code was added.

CBAPI-2180: converted old-style docstrings to Google format

---

bin/linters.sh
codeship-steps.yml
src/cbc_sdk/platform/alerts.py

https://jira.carbonblack.local/browse/CBAPI-2184
Ensure that Flake8 gets run on all branches, and that a break of Flake8 breaks the build.
Tested successfully: Checking in a test change with a Flake8 error broke the build.  That change has been reversed so the build is now successful.

CBAPI-2184: Ensure Flake8 run on all branches.

---

docs/concepts.rst
docs/porting-guide.rst
src/cbc_sdk/platform/base.py

https://jira.carbonblack.local/browse/CBAPI-2132
Add to the concepts and porting guide doc with info about Event Facets, EEDR->Platform
Add better examples to Platform docstrings
Pytest

CBAPI-2132 Event Facet, Platform Documentation

---

src/cbc_sdk/helpers.py
src/tests/uat/process_search_calls.py

https://jira.carbonblack.local/browse/CBAPI-2028
User Acceptance Testing CBC SDK
Test results have been compared to Postman requests

User testing

---

docs/porting-guide.rst

The porting guide doc has 2 mismatched headers -- this PR fixes them

Fix heading levels for porting guide

---

src/cbc_sdk/audit_remediation/__init__.py
src/cbc_sdk/audit_remediation/base.py
src/tests/unit/audit_remediation/test_audit_remediation_base.py
src/tests/unit/audit_remediation/test_scheduled_runs.py
src/tests/unit/fixtures/audit_remediation/mock_templates.py

N/A
Add criteria and template_id search for RunHistory
Add TemplateHistory
Added a unit test

Add criteria and template_id to RunHistory as well as TemplateHistory

---

src/cbc_sdk/rest_api.py

https://github.com/carbonblack/cbapi-python/pull/280
Adding auditlog fetch from cbapi
Existing unit tests pass

Add Auditlog fetch

---

src/cbc_sdk/base.py
src/tests/unit/base/test_base_models.py

https://github.com/carbonblack/carbon-black-cloud-sdk-python/issues/100
Remove refreshable text when printing UnrefreshableModel
Added a new unit test

Prevent refreshable text when printing an UnrefreshableModel

---

src/cbc_sdk/endpoint_standard/__init__.py
src/cbc_sdk/endpoint_standard/models/usbDevice.yaml
src/cbc_sdk/endpoint_standard/models/usbDeviceApproval.yaml
src/cbc_sdk/endpoint_standard/models/usbDeviceBlock.yaml
src/cbc_sdk/endpoint_standard/usb_device_control.py
src/tests/unit/endpoint_standard/test_usb_device.py
src/tests/unit/endpoint_standard/test_usb_device_approval.py
src/tests/unit/endpoint_standard/test_usb_device_block.py
src/tests/unit/fixtures/endpoint_standard/mock_usb_devices.py

https://jira.carbonblack.local/browse/CBAPI-2241, https://jira.carbonblack.local/browse/CBAPI-2196
Implement the models and queries for the new device control APIs.
Unit tests for all new functionality have been added, covering the new code at 97%.

CBAPI-2241 (CBAPI-2196): Device Control APIs

---

.gitignore
src/tests/uat/device_control_uat.py

Cbapi 2198: User Tests

---

docs/cbc_sdk.endpoint_standard.rst
docs/concepts.rst

https://jira.carbonblack.local/browse/CBAPI-2197
Documentation additions to RTD docs for Device Control.
Previewed changes locally after they were formatted with Sphinx.

CBAPI-2197: Device Control Documentation

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/endpoint_standard/base.py
src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/models/reputation_override.yaml
src/cbc_sdk/platform/processes.py
src/cbc_sdk/platform/reputation.py
src/tests/unit/fixtures/endpoint_standard/mock_enriched_events.py
src/tests/unit/fixtures/platform/mock_reputation_override.py
src/tests/unit/platform/test_reputation_overrides.py

CBAPI-2247
Add reputation override model as well as hooks in the Process and Enriched Event models to ban/approve the applications by SHA256
Added additional unit tests and existing unit tests pass

Reputation Override Model

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/base.py
src/cbc_sdk/live_response_api.py
src/cbc_sdk/platform/reputation.py
src/tests/uat/reputation_override_uat.py
src/tests/unit/platform/test_reputation_overrides.py

CBAPI-2249
* Add bulk delete
* Add reputation override UAT
Unit test and User Acceptance testing

Add bulk delete. Add reputation UAT tests

---

docs/device-control.rst
docs/guides-and-resources.rst
docs/index.rst

https://jira.carbonblack.local/browse/CBAPI-2200
Added the initial guide page for device control, within the framework of "Guides and Resources" as sketched out by Kylie and Lisa.
Documentation only, no new code added.

CBAPI-2200: guide page for device control, inside new "guides and resources"

---

docs/concepts.rst
src/cbc_sdk/audit_remediation/base.py
src/cbc_sdk/base.py
src/cbc_sdk/endpoint_standard/usb_device_control.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/devices.py
src/tests/unit/audit_remediation/test_audit_remediation_base.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_platform_process.py

Slack Thread request
* Add support for additional criteria time ranges for Alerts
* Up level _update_criteria and update_criteria functions to a mixin to be added easily to any model that needs criteria
* Up level add_criteria to mixin and remove duplicate _add_criteria as this replicates _update_criteria
Additional unit tests and existing tests pass

Add set_time_range to alerts. Move add/update_criteria to Mixin

---

src/cbc_sdk/enterprise_edr/threat_intelligence.py
src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py
src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py

Aplura slack
Fix updating iocs for report with none or empty iocs
Existing unit tests and one test adjusted to account for update

Fix broken updating iocs for reports

---

src/cbc_sdk/connection.py

Slack thread
'Remote end closed connection without response' error appears to be an issue with the http request closer which can be solved with a few retries.
Manual testing has been completed, this is not feasible to add a unit test

Set max_retries to None to use Connection init logic for retries

---

examples/platform/list_devices.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/platform/models/device.yaml
src/tests/uat/platform_devices_uat.py
src/tests/uat/process_search_calls.py
src/tests/unit/platform/test_devicev6_api.py

https://jira.carbonblack.local/browse/CBAPI-2286
Updated Device Model with the ability to search on deployment_type
Integration and Unit tests provided

Update device model with deployment type search

---

docs/guides-and-resources.rst
docs/reputation-override.rst
src/cbc_sdk/platform/reputation.py

CBAPI-2250
Add tutorial for Reputation Overrides
Existing unit tests pass

Reputation tutorial

---

examples/workload/workloads_search_example.py

https://jira.carbonblack.local/browse/CBAPI-2212
Interactive console script which uses workloads search sdk

Workloads Search example script

---

docs/authentication.rst
docs/cbc_sdk.rst
docs/cbc_sdk.workload.rst
docs/index.rst

https://jira.carbonblack.local/browse/CBAPI-2209
Initial commit for Workloads

add workloads to readthedocs

---

README.md
setup.py

https://jira.carbonblack.local/browse/CBAPI-2375
updated README.md and setup.py to include worload.

CBAPI-2375: Add Workloads to Setup.py and test pip install

---

docs/workload.rst

https://jira.carbonblack.local/browse/CBAPI-2212
Due to paranormal activity(probably due to myself :D) this is a second pull request, with all of the comments from before fixed.

Workloads search guide rtd

---

src/cbc_sdk/connection.py
src/cbc_sdk/workload/sensor_lifecycle.py
src/tests/uat/sensor_lifecycle_uat.py
src/tests/unit/fixtures/CBCSDKMock.py
src/tests/unit/test_base_api.py
src/tests/unit/workload/test_sensor_lifecycle.py

Includes fixes to multipart/form-data API calling to properly send all the
parameters to the server.
https://jira.carbonblack.local/browse/CBAPI-2335
Added UAT script for Sensor Lifecycle Management in Workload API.  Also, altered the design of the "multipart post" and the two SDK calls that make use of it, conforming with what the server requires.
Unit tests have been altered to cover new functionality.  Also, the UAT script itself is a test of the sensor lifecycle management APIs, and it passes.

CBAPI-2335: Sensor Lifecycle UAT

---

docs/changelog.rst

N/A
Modified changelog to omit mention of an unimplemented feature.
Doc update only, no code changes

Release notes update - modified changelog

---

docs/cbc_sdk.workload.rst
docs/changelog.rst

https://jira.carbonblack.local/browse/CBAPI-2425

update changelog and fix workload title in sidebar

---

src/cbc_sdk/platform/processes.py
src/tests/uat/process_search_calls.py
src/tests/unit/fixtures/platform/mock_process.py
src/tests/unit/platform/test_platform_process.py

https://jira.carbonblack.local/browse/CBAPI-2021
Implement the Process Details APIs on the Platform Process object.
Unit tests have been written for the new code. In addition, a call to Process.get_details() has been included in the process_search_calls.py UAT script.

CBAPI-2021: Implement Process Details

---

src/cbc_sdk/platform/devices.py
src/tests/unit/platform/test_platform_devices.py

#144 
Add set_max_rows to device query
Unit test added

Add set_max_rows for device query

---

src/cbc_sdk/platform/alerts.py

Slack thread and email
Add limit to alert query to prevent going past 10k alerts
Manual and CI/CD tests

Add prevention on alerts for going past 10k

---

src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/grants.py
src/cbc_sdk/platform/models/user.yaml
src/cbc_sdk/platform/users.py
src/tests/unit/fixtures/platform/mock_users.py
src/tests/unit/platform/test_users.py

https://jira.carbonblack.local/broswe/CBAPI-2360
Implement User Managemett: the User model object and associated query class.
Unit tests have been written with 97% coverage for all new code.  The code has also been run against the dev01 server with a simple script designed to exercise the GET and PUT of a user.  (Script to be included in a separate comment.)

CBAPI-2360: User Management SDK Code Changes

---

docs/authentication.rst
docs/changelog.rst
docs/concepts.rst
docs/guides-and-resources.rst
docs/live-response-v6-migration.rst
docs/live-response.rst

https://jira.carbonblack.local/browse/CBAPI-2486

CBAPI-2486: Live response guide and migration guide

---

docs/changelog.rst
docs/guides-and-resources.rst
docs/unified-binary-store.rst
src/cbc_sdk/enterprise_edr/ubs.py
src/tests/unit/enterprise_edr/test_enterprise_edr_ubs.py
src/tests/unit/fixtures/enterprise_edr/mock_ubs.py

https://jira.carbonblack.local/browse/CBAPI-2567
https://github.com/carbonblack/carbon-black-cloud-sdk-python/issues/162
download_url is no longer a property, but a method, so the proper way to get the dowload_url will be either file_pull.download_url(expiration_seconds=30) or file_pull.download_url()
With a python script.

Fixing issue 162 and one more bug and increase the test coverage

---

src/cbc_sdk/helpers.py
src/cbc_sdk/rest_api.py
src/tests/uat/process_search_calls.py
src/tests/unit/fixtures/endpoint_standard/mock_usb_devices.py
src/tests/unit/test_helpers.py

https://jira.carbonblack.local/browse/CBAPI-2552

CBAPI-2552: Fix bugs in helpers.py and increase test coverage

---

src/cbc_sdk/platform/grants.py
src/cbc_sdk/platform/users.py
src/tests/unit/fixtures/platform/mock_grants.py
src/tests/unit/fixtures/platform/mock_users.py
src/tests/unit/platform/test_grants.py
src/tests/unit/platform/test_users.py

https://jira.carbonblack.local/browse/CBAPI-2487
Utility functions _aka_ macro-operations for user management in the CBC SDK.  Also enhanced UserQuery to support client-side filtering by E-mail address and login ID.
Unit tests for all new functions have been added, that test right down to the REST calls. Coverage for grants.py is at 96% and users.py is at 99%.

CBAPI-2487 Utility functions AKA Macro-operations

---

examples/platform/attack_stages_export.py
examples/platform/attacks_detected_stopped_export.py

CBAPI-2581
Adding two new examples scripts that replicate legacy dashboard export behavior
Manual testing on the example scripts

Add dashboard export examples

---

src/cbc_sdk/base.py
src/tests/unit/platform/test_platform_process.py

CBAPI-2588
Sort argument was removed during validation. Sort added without fields will only return the sorted property so the fields set to default `*` is added if only sort property is found
CI/CD and manual testing

Fix sort_by function

---

src/cbc_sdk/platform/processes.py
src/tests/uat/process_search_calls.py

N/A
Fix process UAT and add a doc string to explain the set_rows functionality better
CI/CD

Fix Process UAT test and add docstring note

---

docs/changelog.rst
src/tests/uat/live_response_api_uat.py
src/tests/uat/platform_devices_uat.py
src/tests/uat/process_search_calls.py
src/tests/uat/sensor_lifecycle_uat.py
src/tests/uat/vulnerability_assessment_uat.py
src/tests/uat/workloads_search_uat.py

https://jira.carbonblack.local/browse/CBAPI-2619

CBAPI-2619: Small improvements of the uat tests

---

src/cbc_sdk/platform/devices.py

CBAPI-2604
Device base index is 1 not 0 so second pull causes an off by one error
CI/CD and manual

Adjust device base index

---

docs/changelog.rst

N/A
Add details about the refactor to vulnerabilities in the changelog for 1.3.0
N/A

Add more details about vulnerability refactor to changelog

---

docs/guides-and-resources.rst
docs/users-grants.rst
src/cbc_sdk/platform/grants.py
src/cbc_sdk/platform/users.py
src/tests/unit/fixtures/platform/mock_grants.py
src/tests/unit/platform/test_grants.py
src/tests/unit/platform/test_users.py

https://jira.carbonblack.local/browse/CBAPI-2355
Added a user guide for the users and grants APIs in the CBC SDK.
In the process of doing so, there was discovered to be a bug in the implementation of `Grant.create_profile()`. This has been fixed.
Tests were adjusted to match bug fix code changes.  All code segments in the guide have been run against an actual server (and in fact were largely copy-pasted from live Python interpreter sessions).

CBAPI-2355: User Mgmt, Grants and Access Profiles - Guide

---

src/cbc_sdk/connection.py
src/tests/unit/test_connection.py

https://jira.carbonblack.local/browse/CBAPI-2608

[CBAPI-2608] Add the ability to provide custom session

---

src/tests/uat/enriched_events_uat.py
src/tests/uat/platform_devices_uat.py

https://jira.carbonblack.local/browse/CBAPI-2648
Stabilizing the UAT tests
Tests passed locally.

Fix a couple of small issues in the UAT tests

---

examples/enterprise_edr/threat_intelligence/stix_taxii.py

EA-19110
Catch error and continue as normal for cabby error
Manual testing

Catch cabby error

---

docs/guides-and-resources.rst
docs/watchlists-feeds-reports.rst

https://jira.carbonblack.local/browse/CBAPI-2681
Added a guide to the "Guides and Resources" section of the documentation covering watchlists, feeds, reports, and IOCs.
Documentation only.

CBAPI-2681: Guide for Watchlists in CBC SDK

---

src/cbc_sdk/endpoint_standard/base.py
src/cbc_sdk/platform/processes.py
src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events.py
src/tests/unit/fixtures/platform/mock_process.py
src/tests/unit/platform/test_platform_process.py

Fix endless loop

---

docs/unified-binary-store.rst
src/cbc_sdk/enterprise_edr/ubs.py
src/tests/unit/enterprise_edr/test_enterprise_edr_ubs.py

Slack Thread
Adjust comparison on UBS download to be case insensitive
Manual and CI/CD

Add case insensitivity for UBS download

---

src/tests/uat/live_response_api_async_uat.py
src/tests/uat/live_response_api_uat.py

Change device id

---

src/cbc_sdk/endpoint_standard/__init__.py
src/cbc_sdk/endpoint_standard/models/recommendation.yaml
src/cbc_sdk/endpoint_standard/models/recommendation_application.yaml
src/cbc_sdk/endpoint_standard/models/recommendation_impact.yaml
src/cbc_sdk/endpoint_standard/models/recommendation_new_rule.yaml
src/cbc_sdk/endpoint_standard/models/recommendation_workflow.yaml
src/cbc_sdk/endpoint_standard/recommendation.py
src/tests/unit/endpoint_standard/test_recommendation.py
src/tests/unit/fixtures/endpoint_standard/mock_recommendation.py

https://jira.carbonblack.local/browse/CBAPI-2380
Add support for recommendation API to CBC SDK.
Unit test coverage for newly added source is at 95%.

CBAPI-2380 - CBC SDK - add recommendation code

---

docs/cbc_sdk.platform.rst
docs/cbc_sdk.workload.rst
docs/changelog.rst
docs/concepts.rst
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/grants.py

Email
Fix module references to match examples
Fix a few sphinx warnings
Verified documentation locally

Fix concepts.rst and a few sphinx warnings

---

src/cbc_sdk/endpoint_standard/recommendation.py
src/tests/uat/recommendation_uat.py
src/tests/unit/endpoint_standard/test_recommendation.py
src/tests/unit/fixtures/endpoint_standard/mock_recommendation.py

https://jira.carbonblack.local/browse/CBAPI-2617
High-level UAT tests for the Recommendations API, as well as other necessary changes to bring the code into line with reality.
This _is_ a test script.  It has been run against dev01. Also, necessary unit tests have been added/altered where existing code was. Code coverage on the main source file is 95%.

CBAPI-2617: CBC SDK - add high-level tests (Recommendations)

---

docs/watchlists-feeds-reports.rst

Addresses a couple of typos identified here:
https://carbonblack.slack.com/archives/CMUB2T118/p1632523824234600
https://carbonblack.slack.com/archives/CMUB2T118/p1632530816239200

update a couple of typos in Watchlists guide

---

docs/unified-binary-store.rst

Corrected a couple of typos, and while I was there I took time to re-frame some prose to read more cleanly

Copy edits for UBS guide

---

docs/recommendations.rst
src/cbc_sdk/base.py
src/cbc_sdk/endpoint_standard/recommendation.py
src/cbc_sdk/enterprise_edr/threat_intelligence.py
src/cbc_sdk/platform/grants.py
src/tests/unit/base/test_base_models.py

https://jira.carbonblack.local/browse/CBAPI-3019
Improve `__str__()` handling for objects inheriting from NewBaseModel.  Proper subobject rendering has been implemented for Recommendation, Feed, and Report objects as a testbed. Recommendation guide page has also been updated with new output, especially for the first example where full objects are dumped, not just summaries.
Unit tests have been created for the newly-added functionality, especially `_str_attr_line()` which is the "core rendering engine" of the new code.

CBAPI-3019: Add improved string representation to Recommendation object

---

docs/authentication.rst

CBAPI-3196
Fix broken example in authentication guide
N/A

Fix broken example

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
requirements.txt

Please check if your PR fulfils the following requirements:
3163
Usage:
```console
$ pip install -r requirements.txt 
$ pre-commit install 
```
And then try to commit wrongly formated code.
Most of the argumentation is presented in ticket 3163.

Add pre-commit config

---

CONTRIBUTING.md
README.md
docker/docs/Dockerfile
docker/docs/docker-compose.yml
docker/docs/start
docs/Makefile
docs/cbc_sdk.credential_providers.rst
docs/cbc_sdk.endpoint_standard.rst
docs/cbc_sdk.platform.rst
docs/modules.rst

Please check if your PR fulfils the following requirements:
CBAPI-2985
Add an automatic docker build with live edit for the documentation.

Add docker build for the documentation

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/vulnerability_assessment.py
src/tests/unit/base/test_queries.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_devicev6_api.py
src/tests/unit/platform/test_reputation_overrides.py

N/A
Optimize the API request when performing query slicing
Existing and new tests pass

Optimize query slicing

---

docs/authentication.rst
requirements.txt
src/cbc_sdk/credential_providers/__init__.py
src/cbc_sdk/credential_providers/aws_sm_credential_provider.py
src/tests/unit/credential_providers/test_aws_secrets_manager.py

CBAPI-2274
Create a AWS Secrets Manger credential provider
Unit Tests

CBAPI-2274: Add AWS Secrets Manager as credential provider

---

setup.py

Add `boto3` to `setup.py`
CBAPI-2274

Add `boto3` to `setup.py`

---

docs/vulnerabilities.rst

https://jira.carbonblack.local/browse/CBAPI-3118
In progress draft of SDK guide for Vulnerabilities

Vulnerabilities SDK guide in progress

---

src/cbc_sdk/platform/processes.py

Discovered on call with customer
Modify docstring for ProcessFacet model to better indicate support for full query string
N/A

Add alternative for process_guid in ProcessFacet model

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/audit_remediation/base.py

https://jira.carbonblack.local/browse/CBAPI-3435
* Linked "jobs" module contents onto Platform API page.
* Added more information to the docstring for `ResultQuery.async_export()`, mentioning what to do with the Job object once the caller gets it.
New docs viewed locally to ensure that changes are reflected in generated documentation.

CBAPI-3435: Added info for async export with jobs

---

README.md
docs/guides-and-resources.rst
docs/live-query.rst

Found during release testing.
Added a link within the docs guides.
Added the theme to install instructions about sphinx for rtd generation.
Generated docs and viewed locally.

Added link on the guides page for the vulnerabilities guide.

---

docs/alerts.rst

https://jira.carbonblack.local/browse/CBAPI-3599
Added information on container runtime alerts to the SDK docs. It's mainly an overview of what those events are for.
Documentation update only; no code changes.

CBAPI-3599: Update SDK Alerts Guide to include CONTAINER_RUNTIME alerts

---

docs/cbc_sdk.workload.rst
src/cbc_sdk/errors.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/workload/__init__.py
src/cbc_sdk/workload/nsx_remediation.py
src/tests/uat/nsx_remediation_uat.py
src/tests/unit/fixtures/workload/mock_nsx_remediation.py
src/tests/unit/workload/test_nsx_remediation.py

https://jira.carbonblack.local/browse/CBAPI-3574
Added the NSX Remediation functionality to the SDK.  This includes a new `NSXRemediationJob` object and additions to the `Device` object.
Unit tests have been written with 100% code coverage of all added code.  A UAT script has also been added and has been tested against the dev01 server test organization.

CBAPI-3574: Add NSX Remediation to SDK

---

README.md
docs/requirements.txt
requirements.txt
setup.py

#255 
CBAPI-3400
A question has been raised about our dependencies, I have investigated the issue and located the unused packages and removed it. Thanks to [@sevdog](https://github.com/sevdog) about helping for those.
Ran the unit tests, and docs.

CBAPI-3400 Remove unused dependancies

---

src/cbc_sdk/rest_api.py

CBAPI-3907
Increase default for `thread_pool_count` and add to docstring
Manual

Set threat_pool_count default to 3 and document in docstring

---

examples/platform/set_user_enable.py
src/cbc_sdk/platform/models/grant.yaml
src/tests/unit/fixtures/platform/mock_grants.py
src/tests/unit/platform/test_grants.py

CBAPI-2673
Remove revoked from CBC SDK for grants
Manual and unit tests

Remove revoked from grants

---

src/cbc_sdk/platform/models/device.yaml

CBAPI-3891 - update information on fields that are never populated.
Descriptions on three fields in Device.
Reviewed documents locally.

Updated description for three unused sensor fields on device info.

---

docs/watchlists-feeds-reports.rst

CBAPI-3869
I wanted to create some quick snippets that you can just take and run since I found myself digging and creating those all over again, so I've put them into the guide. I can see that some of the code is being duplicated and I am not sure how to structure it but whenever I look for something IOC-related I just scroll down to the IOC section of that document (I believe the other people are doing the same thing). I am open to suggestions on how to structure the whole thing.

CBAPI - 3869 - Enhance the watchlist-feeds-reports guide

---

requirements.txt
src/cbc_sdk/connection.py
src/cbc_sdk/credentials.py
src/cbc_sdk/helpers.py
src/tests/uat/csp_oauth.py
src/tests/uat/proxy_test.py
src/tests/unit/base/test_base_models.py
src/tests/unit/base/test_queries.py
src/tests/unit/credential_providers/test_aws_secrets_manager.py
src/tests/unit/credential_providers/test_registry.py
src/tests/unit/test_base_api.py
src/tests/unit/test_connection.py
src/tests/unit/test_credentials.py
src/tests/unit/test_helpers.py

CBAPI-2553
Add CSP OAuth tokens to Credential
Manual integration tests and existing unit tests

CSP OAuth Token Support

---

src/tests/uat/watchlist_feed_uat.py

Note: The watchlist UAT script will currently fail due to bugs in https://jira.carbonblack.local/browse/CBAPI-3981
This tests two issues found during SDK 1.4.0 release testing.
1. Using the print() function on a report object fails.
2. Attempting to add a report to an existing watchlist attempts to create a new watchlist instead of appending.
Testing manually with verification in CBC Console.

Added test to add a new report to an existing watchlist

---

src/cbc_sdk/base.py
src/cbc_sdk/enterprise_edr/threat_intelligence.py
src/tests/uat/watchlist_feed_uat.py
src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py
src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py

https://jira.carbonblack.local/browse/CBAPI-3981
Fixed:
1. Prettyprint code fixed to properly print subobjects which are lists of zero length.
2. UAT code fixed to generate better names for watchlists so tests don't fail by expecting a watchlist to be new
3. `Watchlist.save()` now calls through to `Watchlist.update()` if the watchlist already exists
Unit tests have been modified to reflect the changes, and all pas. UAT script now completes successfully, and failing `print(r)` has been uncommented.

CBAPI-3981: Watchlist issue

---

src/tests/uat/policy_uat.py

CBAPI-3642 - Policy Simplification - SDK UAT test created
Documented manual steps to test policy functions.
Used during 1.4 release testing.

Manual UAT test for Policy functions.

---

docs/authentication.rst
docs/getting-started.rst
docs/index.rst

- [] Docs have been reviewed and added / updated if needed (for bug fixes / features)
https://jira.carbonblack.local/browse/CBAPI-3885
RTD information was missing for the OAuth authentication method.

Add OAuth information in RTD

---

src/cbc_sdk/enterprise_edr/threat_intelligence.py
src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py
src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py

CBAPI-4149
Add alertable field to feeds
Unit tests

Add alertable to feeds

---

examples/platform/container_runtime_alerts.py

https://jira.carbonblack.local/browse/CBAPI-4247
Take the script fragments from https://carbonblack.vmware.com/blog/carbon-black-container-apis-just-got-better-get-container-runtime-alerts-cbc-python-sdk and turn them into a new example script.
New script has been executed to validate it works correctly.  Script is also well-documented to show the functionality.

CBAPI-4247: Add example script for Container Alerts

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/asset_groups.py
src/cbc_sdk/platform/models/asset_group.yaml
src/tests/unit/fixtures/platform/mock_asset_groups.py
src/tests/unit/platform/test_asset_groups.py

https://jira.carbonblack.local/browse/CBAPI-4249
Added basic AssetGroup model object that supports the four basic CRUD operations.  All these operations are tested in the unit tests.
Unit tests for all CRUD operations have been written.  Code coverage of new file at 100%.

CBAPI-4249: Asset Group Support in CBC SDK p1 - Model Object

---

src/cbc_sdk/platform/asset_groups.py
src/tests/unit/fixtures/platform/mock_asset_groups.py
src/tests/unit/platform/test_asset_groups.py

https://jira.carbonblack.local/browse/CBAPI-4256
Added the "query" functionality for Asset Groups, mainly consisting of the `AssetGroupQuery` object.
Unit tests have been written to cover the new code. Coverage for the file as a whole stands at 97%.

CBAPI-4256 - Asset Group Support in CBC SDK p2 - Query Object

---

src/cbc_sdk/endpoint_standard/base.py
src/cbc_sdk/platform/processes.py
src/tests/unit/base/test_base_models.py
src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events.py
src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py
src/tests/unit/enterprise_edr/test_enterprise_edr_ubs.py
src/tests/unit/fixtures/CBCSDKMock.py
src/tests/unit/fixtures/endpoint_standard/mock_enriched_events.py
src/tests/unit/fixtures/platform/mock_process.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_platform_dynamic_reference.py
src/tests/unit/platform/test_platform_events.py
src/tests/unit/platform/test_platform_process.py
src/tests/unit/platform/test_platform_query.py
src/tests/unit/platform/test_policies.py
src/tests/unit/platform/test_reputation_overrides.py
src/tests/unit/platform/test_vulnerability_assessment.py
src/tests/unit/test_helpers.py
src/tests/unit/test_live_response_api.py
src/tests/unit/test_rest_api.py

CBAPI-4244
Remove v1 status url and replace with results fetch with 1 result
Existing tests continue to pass

Remove v1 status url

---

docs/changelog.rst
docs/developing-credential-providers.rst
docs/differential-analysis.rst
src/cbc_sdk/audit_remediation/base.py
src/cbc_sdk/audit_remediation/differential.py
src/cbc_sdk/endpoint_standard/usb_device_control.py
src/cbc_sdk/live_response_api.py
src/cbc_sdk/platform/processes.py

- [] New and existing tests pass locally with the changes.
Fixing formatting in rtd and some errors in the generation.
Updates to formatting for read the docs.
No

RTD fixes Jan 2023

---

examples/platform/export_users_grants.py

https://jira.carbonblack.local/browse/CBAPI-4303
Added script under `examples/` to export users with grant and role information. Script supports the following:
* Matches up users and access grants with minimal API calls to the server
* Supports filtering by one or more roles
* Supports output in JSON or CSV format, to either standard output or a file
Script does _not_ support sorting of the output; this is by design and keeping with the requirements.
Script has been run against several environments, including a `prod02` environment, testing the various options.

CBAPI-4303: Export Users with Access Profiles/Role assignment

---

src/cbc_sdk/platform/vulnerability_assessment.py
src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py
src/tests/unit/fixtures/platform/mock_vulnerabilities.py
src/tests/unit/platform/test_vulnerability_assessment.py

CBAPI-4238
Partial work for dismiss, undismiss, and dismiss edit of vulnerabilities. Not complete or tested; checking in due to illness so it can be picked up

Dismiss vulnerabilities

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/models/network_threat_metadata.yaml
src/cbc_sdk/platform/models/observation.yaml
src/cbc_sdk/platform/network_threat_metadata.py
src/cbc_sdk/platform/observations.py
src/cbc_sdk/rest_api.py
src/tests/unit/fixtures/platform/mock_network_threat_metadata.py
src/tests/unit/fixtures/platform/mock_observations.py
src/tests/unit/platform/test_network_threat_metadata.py
src/tests/unit/platform/test_observations.py
src/tests/unit/test_base_api.py
src/tests/unit/test_rest_api.py

Adding network threat meta data lookup (tms_rule_id is not currently returned from Observations, but will be)

Cbapi 4452 network threat metadata

---

src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/observations.py
src/cbc_sdk/rest_api.py
src/tests/uat/observations_uat.py
src/tests/unit/fixtures/mock_rest_api.py
src/tests/unit/fixtures/platform/mock_observations.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_observations.py
src/tests/unit/test_rest_api.py

* UAT for Observations
* static methods for suggestions for both Observation / Alert
* static method for bulk_get_details
* remove validation & suggestions from rest_api.

UAT Observations + improvements based on KK discussion

---

docs/concepts.rst

CBAPI-4547 add static concept

---

src/cbc_sdk/platform/vulnerability_assessment.py
src/tests/uat/vulnerability_assessment_uat.py
src/tests/unit/platform/test_vulnerability_assessment.py

CBAPI-4275
Added a test to Dismiss and Undismiss Vulnerability.
Removed "ALL" as an option for vulnerabilityVisibility to align with CBC behaviour.
Changes are a test script that was run and verified manually.

UAT Update for Hide Vulnerability

---

examples/platform/policy_service_crud_operations.py
src/tests/uat/policy_uat.py

Slack request
Remove `values()` on rules iteration as it's a list not a dictionary
Not tested only manual inspection of the expected results from the API

Fix bug in listing policy rules

---

docs/alerts.rst
src/cbc_sdk/platform/alerts.py

https://jira.carbonblack.local/browse/CBAPI-3009

empty list parameter info

---

docs/alerts.rst

https://jira.carbonblack.local/browse/CBAPI-4221
Adding sample script for retrieving alerts from multiple orgs

Multi org alerts fixed

---

README.md
docker/rhel/Dockerfile
docs/requirements.txt

N/A
Investigating readthedocs
Manual and Codeship

Remove unused run command

---

docs/guides-and-resources.rst
docs/policy.rst
examples/platform/policy_core_prevention.py
examples/platform/policy_host_based_firewall.py
examples/platform/policy_service_crud_operations.py

CBAPI-4556 - part of the host-based firewall function.
Example scripts to assist adoption.
Runs on my machine, verified in CBC console.

HBFW Example Script

---

README.md
requirements.txt
setup.py

https://jira.carbonblack.local/browse/CBAPI-4437
Upgrade the "pinned" version of pymox in `requirements.txt` to 1.0.0.
Complete pytest run done; finishes successfully with no warning messages.

CBAPI-4437: Upgraded pymox to 1.0.0

---

codeship-services.yml
codeship-steps.yml
docker/python3.11/Dockerfile

https://jira.carbonblack.local/browse/CBAPI-4368
Added automated testing support for Python 3.11.
Codeship run for this branch shows Python 3.11 testing completed successfully.

CBAPI-4368 - Add automated testing support for Python 3.11

---

src/cbc_sdk/platform/policy_ruleconfigs.py
src/tests/unit/fixtures/CBCSDKMock.py
src/tests/unit/fixtures/platform/mock_policy_ruleconfigs.py
src/tests/unit/platform/test_devicev6_api.py
src/tests/unit/platform/test_policy_ruleconfigs.py

https://jira.carbonblack.local/browse/CBAPI-4379
Add support for the "copy HBFW rules to policy" and "export HBFW rules" endpoints to the `HostBasedFirewallRuleConfig`.
Unit tests written for all new functions. Test coverage at 97%.

CBAPI-4379: Add Advanced Host-Based Firewall Endpoints to Policy

---

src/cbc_sdk/audit_remediation/base.py
src/cbc_sdk/base.py
src/cbc_sdk/connection.py
src/cbc_sdk/endpoint_standard/usb_device_control.py
src/cbc_sdk/errors.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/platform/policies.py
src/cbc_sdk/platform/reputation.py
src/cbc_sdk/platform/users.py
src/cbc_sdk/rest_api.py
src/cbc_sdk/workload/nsx_remediation.py
src/tests/unit/base/test_base_models.py
src/tests/unit/fixtures/CBCSDKMock.py
src/tests/unit/fixtures/stubresponse.py
src/tests/unit/test_base_api.py
src/tests/unit/test_connection.py

https://jira.carbonblack.local/browse/CBAPI-4734
Added "uri" parameters and fields to the ServerError and ClientError exception classes, and filled in context information from the places where they're raised.
Additional test items have been added to ensure the URL is passed through properly. All existing tests pass with these changes.

CBAPI-4734: Bulletproof Catching of Server Errors 500	

---

docs/policy.rst
docs/workload.rst

fixed typo on workload guide

---

docs/index.rst
docs/policy.rst
docs/vulnerabilities.rst
docs/workload.rst

https://jira.carbonblack.local/browse/CBAPI-4782

Adding missing items to guides menu

---

docs/policy.rst
examples/platform/policy_data_collection.py
examples/platform/policy_host_based_firewall.py

As part of release testing extended the policy example scripts to include Enabling and Disabling Auth Event Collection.
New policy_data_collection example script.
Verified in the Carbon Black Console.

Auth Event Example

---

docs/audit-log.rst
examples/platform/audit_log.py

Example script that polls for Audit Log
Run locally.

Example script to poll for audit logs

---

examples/platform/container_runtime_alerts.py
src/cbc_sdk/connection.py
src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_platform_models.py

pull request fixes

---

src/cbc_sdk/rest_api.py

fixed typo.

---

src/cbc_sdk/endpoint_standard/usb_device_control.py
src/tests/unit/endpoint_standard/test_usb_device_approval.py

https://jira.carbonblack.local/browse/CBAPI-4888
Implement the `export()` function on `USBDeviceApprovalQuery` (as for CBAPI-4789, but for the device approvals rather than the devices themselves).
Unit tests have been added for new function; coverage of relevant file stands at 97%.  Run log for this function is as follows: 
[usb_device_approval_export.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/12165336/usb_device_approval_export.log)

CBAPI-4888: Add External Device Approvals Export route

---

.pre-commit-config.yaml
src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv6_api.py

CBAPI-4676
Add set rows for BaseAlertSearchQuery
Unit and manual

Add set rows for BaseAlertSearchQuery

---

docs/alerts.rst
src/cbc_sdk/base.py
src/tests/unit/base/test_base_models.py

N/A
Remove and protect members we don't want to expose to Readthedocs
Reviewed docs for expected generation and cleaned up code to utilize new _new_object func

Protect new_object() and remove original_document

---

docs/cbc_sdk.cbcloudapi.rst
docs/cbc_sdk.credential_providers.rst
docs/cbc_sdk.rst
docs/index.rst
docs/live-response.rst

https://jira.carbonblack.local/browse/CBAPI-4902
Pull the documentation for `CBCloudAPI` out into its own page, which goes at the front of the "SDK Documentation" section of the docs, as it's key to everything else about the API.  A short introduction and some examples of creating the `CBCloudAPI` object are included.
Full docs have been built locally and verified that they look like they're supposed to.

CBAPI-4902: Expose CBCloud API in read the docs

---

src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/legacy_alerts.py
src/cbc_sdk/platform/models/alert.yaml
src/cbc_sdk/rest_api.py
src/tests/unit/platform/test_alertsv6_api.py

[CBAPI-4813](https://jira.carbonblack.local/browse/CBAPI-4813)
Fixes v6 unit tests with the exception of test_load_workload. Looks like may require additional changes

Cpapi 4813 v6 unit tests

---

src/cbc_sdk/platform/devices.py

https://github.com/carbonblack/carbon-black-cloud-sdk-python/issues/397
Add new deployment types
Unit tests

Add new deployment types

---

README.md
docs/guides.rst
docs/live-response-v6-migration.rst
docs/porting-guide.rst

CBAPI-4990
* Updated porting guide to reflect latest APIs
* Updated live response migration guide with links
* Updated README wrt generating docs locally
Reviewed rtd generated for this PR.
https://carbon-black-cloud-python-sdk--402.org.readthedocs.build/en/402/

Update Porting Guide

---

src/cbc_sdk/platform/vulnerability_assessment.py
src/tests/unit/platform/test_vulnerability_assessment.py

Updated unit tests with a new value and ensured they pass.

Updated valid os_types for  vulnerabilities

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv7_api.py

CBAPI-4997, CBAPI-5032
* Do not add query to the request body if empty
* Do not validate if query is empty

Do not add query if empty, do not validate if query is empty

---

src/cbc_sdk/audit_remediation/base.py
src/cbc_sdk/base.py
src/cbc_sdk/endpoint_standard/recommendation.py
src/cbc_sdk/endpoint_standard/usb_device_control.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/platform/events.py
src/cbc_sdk/platform/reputation.py
src/cbc_sdk/platform/vulnerability_assessment.py
src/cbc_sdk/workload/vm_workloads_search.py
src/tests/unit/audit_remediation/test_audit_remediation_base.py
src/tests/unit/fixtures/workload/mock_search.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_alertsv7_api.py
src/tests/unit/platform/test_devicev6_api.py

CBAPI-5000 & CBAPI-5035
* criteria is not added unless not empty
* q is removed after the validation is done
locally

Remove q added by validation request, do not add criteria if empty

---

src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_alertsv7_api.py

CBAPI-5033
Adjust when start is set
Unit tests

Adjust alert start

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/legacy_alerts.py
src/tests/unit/fixtures/platform/mock_alerts_v7.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_alertsv7_api.py

Removed validation enums that were not being used.
Updated invalid examples in base.py
See commit messages for details.
CBAPI-5022
E2E locally and updated unit tests where needed.

Relax enum validation

---

src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv7_api.py

Fixing bug introduced in PR #413 but missed during testing
New unit test added

Replace Alert with self in Alert __getattr__

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/processes.py
src/tests/unit/base/test_base_models.py
src/tests/unit/fixtures/platform/mock_process.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_platform_dynamic_reference.py
src/tests/unit/platform/test_platform_events.py
src/tests/unit/platform/test_platform_process.py
src/tests/unit/platform/test_platform_query.py
src/tests/unit/platform/test_reputation_overrides.py

https://jira.carbonblack.local/browse/CBAPI-4995
Change all the GET calls on /api/investigate/v1/orgs/{orgkey}/processes/search_validation to the newer POST calls on /api/investigate/v2/orgs/{orgkey}/processes/search_validation.  Also fixed up docstrings in the process code to better match the docstring spec.
Tests have been modified to pass with the new call.  Process search has been executed against `prod02`, mainly to test a new example being added to the docstrings.

CBAPI-4995: Update SDK to use POST search validation instead of GET	

---

src/cbc_sdk/base.py
src/tests/unit/platform/test_alertsv7_api.py
src/tests/unit/platform/test_platform_process.py

CBAPI-5070 - criteria and exclusion are valid with integer lists as well as string lists.  Relax the validation to allow this.
Ready to go with SDK 1.5.0

Relax criteria and exclusion validation

---

src/cbc_sdk/platform/alerts.py
src/tests/unit/fixtures/platform/mock_alert_v6_v7_compatibility.py
src/tests/unit/platform/test_alertsv6_api.py
src/tests/unit/platform/test_alertsv7_api.py

CBAPI-4766
Add threat notes and alert/threat history
Unit tests and manual E2E

Alert notes

---

src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv7_api.py

Add threat tags
Manual and unit tests

Add threat tags

---

README.md
docs/changelog.rst

https://jira.carbonblack.local/browse/CBAPI-4818
Set the release date to today, in accordance with Step 1 of the "Releasing the SDK" process.
Doc update only, no codechanges.

CBAPI-4818: Set release date for Release 1.5.0

---

README.md
docs/changelog.rst

https://jira.carbonblack.local/browse/CBAPI-4818
Merge of Release 1.5.0 branch to `develop`, in accordance with Step 5 of the SDK Release process.
Changes have already been tested and approved previously.

CBAPI-4818: Release 1.5.0 Merge to Develop

---

docs/alerts.rst
docs/guides.rst
docs/notifications-migration.rst

Adding a Notifications migration guide - mostly moving from the Alerts Guide, but also added more context and refs to other information. 
And fixed a bit of formatting.
Reviewed RTD on this PR.

Added migration info from notifications to alerts in the SDK

---

src/cbc_sdk/base.py
src/tests/unit/platform/test_alertsv7_api.py

https://jira.carbonblack.local/browse/CBAPI-5139
Changed base method all() to return a list, as documented, instead of a generator.
Confirmed that list(list(gen())) and list(gen()) both result in a list so it's not breaking.
Unit test added  and manual execution.

corrected all() to return list instead of generator

---

examples/platform/alerts_common_scenarios.py
src/cbc_sdk/base.py
src/cbc_sdk/platform/alerts.py
src/tests/unit/fixtures/platform/mock_alerts_v7.py
src/tests/unit/platform/test_alertsv7_api.py

- [x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x ] Tests have been added that prove the fix is effective or that the feature works.
- [x ] New and existing tests pass locally with the changes.
- [ x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [ x] A self-review of the code has been done.
[CBAPI-5087](https://jira.carbonblack.local/browse/CBAPI-5087)
adds a helper function to the GroupAlert object that creates the AlertSearchQuery for all alerts associated with a given GroupAlert object
- [ x] No
added to common scenarios

Cbapi 5087 searched group alert helper function

---

docs/live-query.rst
src/cbc_sdk/audit_remediation/base.py
src/cbc_sdk/base.py
src/tests/unit/audit_remediation/test_audit_remediation_base.py
src/tests/unit/fixtures/audit_remediation/mock_scroll.py

CBAPI-5182
Add scroll functionality for Live Query Result
Manual and unit tests

Live query scroll

---

docs/alerts.rst

[CBAPI_4828](https://jira.carbonblack.local/browse/CBAPI-4828)
updated RTD for group alerts
local build of RTD

Cbapi 4828 rtd guide

---

docs/cbc_sdk.platform.rst
src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/asset_groups.py
src/cbc_sdk/platform/devices.py
src/cbc_sdk/platform/policies.py
src/cbc_sdk/platform/previewer.py
src/tests/unit/fixtures/platform/mock_asset_groups.py
src/tests/unit/fixtures/platform/mock_devices.py
src/tests/unit/fixtures/platform/mock_policies.py
src/tests/unit/platform/test_asset_groups.py
src/tests/unit/platform/test_platform_devices.py
src/tests/unit/platform/test_policies.py

https://jira.carbonblack.local/browse/CBAPI-4252
Added many functions to `AssetGroup`, `Device`, and `Policy` that implement the various preview operations.
Unit tests have been created for all new functions; coverage is at 99% for `asset_groups.py`, 96% for `devices.py`, and 97% for `policies.py`.  Log file from live run is here: [preview_funcs_changes.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/13954974/preview_funcs_changes.log)

CBAPI-4252: Asset Groups: Get Effective Policy for Device

---

examples/platform/asset_groups.py

CBAPI-4250
Added an example of using Asset Groups.
Includes Create, Update, Delete an Asset Group.
Also shows how to step to the policy and how to preview the impact of changing policy ranking.
Run locally.

Added example script with CRUD of asset groups and preview policy rank

---

examples/platform/alerts_common_scenarios.py
src/cbc_sdk/platform/alerts.py
src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py
src/tests/unit/platform/test_alertsv7_api.py

- [x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x ] Tests have been added that prove the fix is effective or that the feature works.
- [x ] New and existing tests pass locally with the changes.
- [x ] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x ] A self-review of the code has been done.
[CBAPI_4825](https://jira.carbonblack.local/browse/CBAPI-4828)
adds method to retrieve wathlist objects from watchlist alerts
- [x ] No
unit tests and tests against the backend via common_scenarios

Cbapi 4825 helper list of watchlists

---

docs/alerts.rst
examples/platform/alerts_common_scenarios.py
src/cbc_sdk/platform/alerts.py

Addressed review comments

---

src/cbc_sdk/platform/devices.py
src/tests/unit/fixtures/platform/mock_devices.py
src/tests/unit/platform/test_devicev6_api.py

CBAPI-5226
Add new device export and scroll capabilities
Unit and manual testing

Device Scroll and Export

---

docs/alerts.rst
docs/differential-analysis.rst
examples/platform/alerts_common_scenarios.py
src/cbc_sdk/base.py
src/cbc_sdk/platform/__init__.py
src/cbc_sdk/platform/alerts.py
src/cbc_sdk/platform/models/grouped_alert.yaml
src/tests/unit/base/test_base_models.py
src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py
src/tests/unit/fixtures/platform/mock_alerts_v7.py
src/tests/unit/platform/test_alertsv7_api.py
src/tests/unit/platform/test_platform_devices.py

https://jira.carbonblack.local/browse/CBC-30087
Extensions to behavior of Alerts v7.  This is a feature branch merge to develop.
Individual PRs have all been tested and reviewed.

Alerts v7 New Features Merge

---

docs/alerts.rst
docs/asset-groups.rst
docs/changelog.rst

Fixing guides so they can be run top to bottom

---

README.md
docs/changelog.rst

https://jira.carbonblack.local/browse/CBAPI-4821
Set the release date for Release 1.5.1 to January 30, 2024.  This is Steps 1 and 2 of the Release Process.
Docs update only, no code changes.

CBAPI-4821: Set Release Date

---

README.md
docs/alerts.rst
docs/asset-groups.rst
docs/changelog.rst

https://jira.carbonblack.local/browse/CBAPI-4821
Merge changes for Release 1.5.1 back to the `develop` branch.  This is Step 5 of the Release Process.
All changes in this branch have been appropriately tested and reviewed.

CBAPI-4821: Release 1.5.1 Merge Back to Develop

---

src/cbc_sdk/platform/jobs.py
src/cbc_sdk/utils.py
src/tests/unit/test_utils.py

https://jira.carbonblack.local/browse/CBAPI-3438
Added the `BackoffHandler` utility class for managing an exponential backoff delay, and employed it in the `Job._await_completion` method.  Added a parameter to both `_await_completion` and `await_completion` for a timeout.
Unit tests have been added for 100% code coverage.

CBAPI-3438: Exponential backoff helper

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/events.py
src/tests/unit/platform/test_platform_process.py

N/A
Fix missing property error
Add short circuit for process events when all events are available
Manual and Unit test

Fix a few small process bugs

---

docs/devices.rst

- [x Docs have been reviewed and added / updated if needed (for bug fixes / features)
https://jira.carbonblack.local/browse/CBAPI-5222
Added a device faceting example to the RTD Guide for devices.
Doc updates only, no code changes.

CBAPI-5222: Update Device RTD Guide

---

src/cbc_sdk/platform/audit.py
src/cbc_sdk/platform/jobs.py
src/tests/unit/fixtures/platform/mock_audit.py
src/tests/unit/fixtures/platform/mock_jobs.py
src/tests/unit/platform/test_audit.py
src/tests/unit/platform/test_devicev6_api.py
src/tests/unit/platform/test_jobs.py

https://jira.carbonblack.local/browse/CBAPI-5260
Implemented the `export()` function on `AuditLogQuery`, analagous to other exports that are used elsewhere.
Unit tests have been added; code coverage stands at 97% on `audit.py`.

CBAPI-5260: Implement Audit Log Export

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/processes.py
src/tests/unit/platform/test_platform_process.py

https://jira.carbonblack.local/browse/PRDTEST-15265
An additional support is added for collapse_field parameter in payload for process search job API.
- [x ] No
This is tested with E2E automation work flows.

1. Added support for collapse field parameter for process search job

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/processes.py
src/tests/unit/platform/test_platform_process.py

https://jira.carbonblack.local/browse/CBC-10998
Add a `collapse_field` parameter to process queries.
This change was originally made by @vsvvj-cb on a forked repo, then merged into this repo as branch `CBC-10998-prod-eng-test-vdp`.  Since that branch was made off a different version of the repository which made rebasing it onto `develop` impractical, I created this new branch and cherry-picked his changes onto it. The resulting code needed deflake8'ing so it would pass Codeship tests.
Test code has been included for new feature.

CBC-10998: Added support for collapse field parameter for process search job

---

README.md
docs/changelog.rst

https://bsg-jira.broadcom.net/browse/CBAPI-5321
Update release date to today.
Doc updates only, no code changes.

CBAPI-5321: updated release date

---

README.md
docs/changelog.rst

https://bsg-jira.broadcom.net/browse/CBAPI-5321
Merge the release-1.5.3 branch back to develop, Step 5 of the SDK Release Process.
In practice, the only changes are to the release date.
Doc updates only, no code changes.

CBAPI-5321: Release merge back to develop

---

src/cbc_sdk/platform/alerts.py
src/tests/unit/platform/test_alertsv7_api.py

N/A
Fixes getitem issue for Alerts
Manual and unit

Fix alerts getitem

---

README.md
docs/changelog.rst

Updated release date for Release 1.5.4 (Step 1 of the Release Process)
Docs only, no code changes

updated release date

---

README.md
docs/changelog.rst

Release 1.5.4 - merge back to develop (Step 5 of Release Process)
Docs only, no code changes

Release 1.5.4 merge to develop

---

setup.py

Move dependency back to install_requires

---

README.md
docs/changelog.rst

update release date for version 1.5.5 (Step 1 of Release Process)
Doc updates only; no code changes.

updated release date for version 1.5.5

---

README.md
docs/changelog.rst

Release 1.5.5 - merge to develop (Step 5 of Release Process)
Doc updates only; no code changes.

Release 1.5.5 - Merge to Develop

---

README.md
docs/changelog.rst

N/A
Set release date for Release 1.5.6. Steps 1 and 2 of the Release Process.
Doc updates only; no code changes.

set release date for 1.5.6

---

src/cbc_sdk/base.py
src/cbc_sdk/platform/processes.py

https://bsg-jira.broadcom.net/browse/PRDTEST-15483
This is support process search validation v2 for customer tests
This was tested locally with customer tests

Adding support for process search validation v2 for customer tests
