carbonblack/carbon-black-cloud-sdk-python

src/cbc_sdk/credential_providers/file_credential_provider.py, src/tests/unit/credential_providers/test_file.py
N/A
I remember being able to use `cb = CBCloudAPI()` which would use the default provide from the file credential provider in CBAPI. I've modified the FileCredentialProvider to use the `default` profile section
Fixed an existing test around this functionality
=> Add supported behavior for file provider with default section

src/cbc_sdk/platform/alerts.py
This is a duplicate of https://github.com/carbonblack/cbapi-python/pull/276
It's a small fix so I didn't do everything, please let me know if it's blocking...
Please check the type of change your PR introduces:
- Issue Number: #68
I ran a request with https://github.com/carbonblack/cbapi-python/blob/master/examples/psc/list_cbanalytics_alerts.py (adapted for this new library of course) that returns ~1k alerts. It was much faster and in my proxy I can see the additional `"rows": 100` parameter while the results are now in chunks of 100
Similar to https://github.com/carbonblack/cbapi-python/pull/252
I chose "100" arbitrarily but you might prefer a different default (by default, API returns 20 rows, while UI requests 50).
Moreover, …
=> PSC Alerts API: requests pages of 100 rows by default

docs/getting-started.rst, examples/README.md, setup.py
It does not generate an issue correctly because the normalization is automatically applied by "pip" and "pypi"
carbon_black_cloud_sdk -> carbon-black-cloud-sdk
See https://www.python.org/dev/peps/pep-0503/#normalized-names and https://pypi.org/project/carbon-black-cloud-sdk/
I did not test the change in setup.py, and obviously I cannot submit to pypi so I let you check if it runs fine :)
=> Pip modules normalized names use dash instead of underscore

src/cbc_sdk/platform/base.py, src/tests/unit/fixtures/platform/mock_events.py, src/tests/unit/platform/test_platform_events.py
https://jira.carbonblack.local/browse/CBAPI-2183 (issue #83)
Add a mechanism to keep from infinitely looping in event and event facet queries where the returned "processed_segments" never reaches the returned "total_segments." The mechanism uses a retry counter that is not incremented (and is, in fact, reset) as long as the "processed_segments" counter is making forward progress; only if it "stalls" does our retry counter get incremented, and, at 10 retries, a TimeoutError is thrown.
(Semi-breaking change: Event and event facet queries may now throw TimeoutError in addition to ApiError.  This only affects code that wants to distinguish the two cases.)
Additional unit tests have been added that trigger the TimeoutError mechanism.
=> CBAPI-2183: added a limit to the retry mechanism on event & event facet queries

src/cbc_sdk/audit_remediation/base.py, src/tests/unit/audit_remediation/test_audit_remediation_base.py, src/tests/unit/fixtures/audit_remediation/mock_runs.py
CBAPI-2233
Live query results returns 400 Bad Request when attempting to fetch more than 10k results
Added a new unit test
=> Limit livequery results to 10k cap to prevent 400 Bad Request

src/cbc_sdk/helpers.py, src/tests/unit/test_helpers.py
Adding a missing argument (args.orgkey) in helpers.py which is used by the example script policy_operations.py.
The argument is used when the script is invoked with environment credentials as parameters. Example:
=> Add missing args orgkey in helpers py

docs/device-control.rst, src/cbc_sdk/endpoint_standard/usb_device_control.py, src/tests/unit/endpoint_standard/test_usb_device.py, src/tests/unit/endpoint_standard/test_usb_device_approval.py, src/tests/unit/endpoint_standard/test_usb_device_block.py, src/tests/unit/fixtures/endpoint_standard/mock_usb_devices.py
Also added the create_from_usb_device method as a quick way to create
approvals from a USB device, and the approve() method on USBDevice that
creates and saves a new USBDeviceApproval all in one go.  The sample doc has
been updated to use the new approve() functionality and also show approval
deletion.
https://jira.carbonblack.local/browse/CBAPI-2290
Added the following changes:
* Updated save() behavior on USBDeviceApproval to allow it to create a new object.
* USBDeviceApproval.create_from_usb_device() to create a USBDeviceApproval object from a USBDevice object.
* approve() method on USBDevice to create and save a new approval for a USBDevice all in one go. (Bruce's suggestion!)
* USBDeviceBlock.create() to create a single …
=> CBAPI-2290: add easy way to add single approvals and blocks

docs/device-control.rst, src/cbc_sdk/platform/__init__.py, src/cbc_sdk/platform/alerts.py, src/cbc_sdk/platform/models/base_alert.yaml, src/tests/unit/platform/test_alertsv6_api.py
https://jira.carbonblack.local/browse/CBAPI-2282
Updated CBC SDK to include DeviceControlAlert and DeviceControlAlertSearchQuery, as well as the valid alert type of DEVICE_CONTROL.  The "device control" guide document has been extended with mention of device control alerts as well.
This PR should also close GitHub issue #117.
New unit tests have been added to test the DeviceControlAlertSearchQuery in the same manner as other alert search queries.  Transcript in the new section of the device control guide is copied from an actual run session searching for the DeviceControlAlert.
=> CBAPI-2282: Update Alerts in SDK to include Device Control Alerts

src/cbc_sdk/connection.py, src/tests/uat/proxy_test.py, src/tests/unit/test_base_api.py
CBAPI-2480
A few CredentialValue properties where not being loaded from the BaseAPI kwargs. Instead of popping all the values off, the kwargs can be passed through to the Credential object.
Added a basic UAT test for proxy testing
Manual and unit tests
=> Add full CredentialValue support to BaseAPI constructor

src/tests/uat/reputation_override_uat.py
Fix reputation_override_uat.py to work as expected when there are additional IT_TOOL and CERT reputation overrides for the same organisation
https://jira.carbonblack.local/browse/CBAPI-2542
Currently the test works only on fresh environment. It fails if there are other reputation overrides of type IT_TOOLS or CERT in the organisation. The proposed solution resolves this issue.
The test passes successfully when performed on non-fresh environment.
=> Enhance reputation_override_uat.py

src/tests/uat/platform_devices_uat.py
https://jira.carbonblack.local/browse/CBAPI-2540 
Adding automated comparison of the results from the SDK and API calls in the platform_devices_uat.py test. Currently, the comparison should be performed manually by the user.
When executed locally, the test passes successfully.
=> Automate comparison of SDK and API calls results in the platform_devices_uat.py test

src/cbc_sdk/platform/grants.py, src/tests/unit/fixtures/platform/mock_grants.py, src/tests/unit/platform/test_grants.py
https://jira.carbonblack.local/browse/CBAPI-2510
Added the get_permitted_roles API to the Grant class. This allows the user to fetch the roles that they are permitted to manage.
Unit test has been added for the new API. All added code is 100% covered. Coverage in grants.py remains at 99%.
=> CBAPI-2510: Add Permitted Roles API to SDK

src/cbc_sdk/base.py, src/cbc_sdk/platform/users.py, src/tests/unit/fixtures/platform/mock_grants.py, src/tests/unit/platform/test_users.py
https://jira.carbonblack.local/browse/CBAPI-2597
I found a serious flaw in a lot of the macro-operations. They don't take into account that users might not _have_ grants.  ( _None_ of the users I can access from dev01 has a grant.)  This adds some defensive code to manage those cases.  For most of these, "user has no grant" becomes a no-op. For some things, like "add profiles," adding them to a user with no grant _creates_ a grant with the profiles to be added.  The grant() operation also offers an optional parameter to create a new grant for a user if they don't have one already.
Unit tests have been expanded to cover the no-grant cases, corresponding to the changes in the code.  Test coverage stands at 100% for users.py.
=> CBAPI-2597: Handle Macro-Operations for Users with No Grant

src/cbc_sdk/base.py, src/cbc_sdk/endpoint_standard/base.py, src/cbc_sdk/platform/alerts.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events_facet.py, src/tests/unit/fixtures/endpoint_standard/mock_enriched_events.py, src/tests/unit/fixtures/endpoint_standard/mock_enriched_events_facet.py, src/tests/unit/platform/test_alertsv6_api.py
https://jira.carbonblack.local/browse/CBAPI-2988
Fixed imports in endpoint_standard/base.py, cbc_sdk/base.py, and platform/alerts.py to import the SDK TimeoutError rather than vanilla TimeoutError (which does not take keyword arguments).  Also added tests to make sure our TimeoutError is thrown properly where it ought to be.
New unit tests have been added to make sure our TimeoutError is thrown properly where it ought to be.  Unit test has been tested by removing the new import and seeing that new test errors out.
=> Cbapi-2988: Resolve: EnrichedEvent search Error: TypeError: TimeoutError does not take keyword arguments

src/cbc_sdk/audit_remediation/base.py, src/cbc_sdk/errors.py, src/tests/unit/audit_remediation/test_audit_remediation_base.py, src/tests/unit/audit_remediation/test_models.py, src/tests/unit/audit_remediation/test_rest_api.py, src/tests/unit/audit_remediation/test_scheduled_runs.py, src/tests/unit/fixtures/CBCSDKMock.py, src/tests/unit/fixtures/audit_remediation/mock_runs.py
https://jira.carbonblack.local/browse/CBAPI-3169
Added several functions to LiveQuery support to make it easier to get runs for a template and results, device summaries, or facets from a run.  Also added asynchronous query support to all LiveQuery queries (including the LiveQuery itself).
Also checked over all docstrings in the LiveQuery code and updated the unit tests that used older mocking to use the CBCSDKMock.
Unit tests added that cover all new code added to LiveQuery.  Coverage on complete source file is at 94%.
=> CBAPI-3169: CBC SDK Live Query Ease of Use Improvements

src/cbc_sdk/audit_remediation/base.py, src/cbc_sdk/connection.py, src/tests/unit/audit_remediation/test_audit_remediation_base.py, src/tests/unit/fixtures/CBCSDKMock.py, src/tests/unit/fixtures/stubresponse.py, src/tests/unit/test_base_api.py
https://jira.carbonblack.local/browse/CBAPI-3328
Added additional method to `ResultQuery`, `export_csv_as_lines()`, that returns the exported CSV as an iterator of lines.  By request of @avanbrunt-cb.
New test script has been written that proves the download works against a live environment.  Test script (with internal data redacted) follows.
```
#!/usr/bin/env python
from cbc_sdk import CBCloudAPI
from cbc_sdk.audit_remediation import Run
api = CBCloudAPI(profile='[REDACTED]')
run = api.select(Run, '[REDACTED]')
for line in run.query_results().export_csv_as_lines():
print(line)
```
Additional unit tests have been written for the new functionality.  All new code is covered.
=> CBAPI-3328: SDK: Export Live Query Results - Line-by-Line Iteration

src/cbc_sdk/base.py, src/tests/unit/base/test_base_models.py
https://jira.carbonblack.local/browse/CBAPI-3298
The code that renders objects has been modified to handle dicts as attribute values of the top-level object being rendered, to improve the appearance of examples in the Vulnerability guide document.
Sample output (for a Vulnerability object):
```
Vulnerability object, bound to https://defense.conferdeploy.net.
-------------------------------------------------------------------------------
affected_assets: [list:1 item]:
[0]: DESKTOP-ABCDEFG
category: APP
cve_id: CVE-1999-0794
device_count: 1
os_info: [dict] {
os_arch: 64-bit
os_name: Microsoft Windows 10 Pro
os_type: WINDOWS
os_version: 10.0.18363
}
os_product_id: 37_282511
product_info: [dict] {
arch:
product: Microsoft Office …
```
=> CBAPI-3298: Vulnerabilities SDK - Add code to handle printing

examples/enterprise_edr/threat_intelligence/stix_taxii.py, src/cbc_sdk/enterprise_edr/threat_intelligence.py
EA-20291
Sometimes the STIX feed might give just the netloc of a URI, sometimes a full URL and that depends on the feed. Since that we are parsing it into an `IOC_V2.link ` where the field must be `netconn_domain` (targetting FQDN) the fix is to remove the `validation.url` and replace it with `validation.domain` instead while validating the IOC. On the other hand, we should pass the netloc part of the URI instead of the whole URI while attaching the IOC to the Report.
Manually with STIX_v1.2 XML Files and with 2 STIX Feeds (1 confidential and 1 open-source).
=> EA-20291 Fix Exception: `link should be valid url`

src/cbc_sdk/enterprise_edr/threat_intelligence.py, src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py, src/tests/unit/fixtures/enterprise_edr/mock_threatintel.py
https://jira.carbonblack.local/browse/CBAPI-3386, also GitHub #246 
Changed the way the "ignore" API is called to use a "feed id-report id" syntax for the report if the report is part of a feed.  Tests have shown that this syntax works even if the feed in question is _not_ subscribed to by any watchlist.
Unit tests have been added to test the new code paths and the means of generating the feed ID sent to the server. All added code is covered.  Tests have also been run using the following script to query and set the ignore status of a report in a feed that is not subscribed to by any watchlist.
```
#!/usr/bin/env python
import sys
from cbc_sdk.helpers import build_cli_parser, get_cb_cloud_object
from cbc_sdk.enterprise_edr import …
```
=> CBAPI-3336: Allow Get/Set Ignore Status Even If Report is Part of a Feed

src/cbc_sdk/base.py, src/tests/unit/base/test_base_models.py
https://jira.carbonblack.local/browse/CBAPI-3415
Reported by Kylie: In some cases, printing a Result object would cause an exception.  This happened with Results that had no fields, and hence their "fields" field was an empty dict.  Enhancements have been made in the code to properly print an empty dict, and to keep this exception from ever being raised again.
With this fix in place, a Result object with an empty dict now prints as follows:
```
Result object, bound to https://defense.conferdeploy.net.
-------------------------------------------------------------------------------
device: [dict] {
id: [elided]
name: [elided]
os: WINDOWS
policy_id: [elided]
policy_name: default
}
device_message: 
fields: [dict] {
}
id: [elided] …
```
=> CBAPI-3415: fixed rendering of empty dicts inside an object

src/cbc_sdk/audit_remediation/base.py, src/cbc_sdk/connection.py, src/cbc_sdk/platform/__init__.py, src/cbc_sdk/platform/jobs.py, src/cbc_sdk/platform/models/job.yaml, src/tests/unit/audit_remediation/test_audit_remediation_base.py, src/tests/unit/fixtures/CBCSDKMock.py, src/tests/unit/fixtures/platform/mock_jobs.py, src/tests/unit/platform/test_jobs.py, src/tests/unit/test_base_api.py
https://jira.carbonblack.local/browse/CBAPI-3296
Added support for retrieving results for a Live Query via an asynchronous job.  Includes adding support for the Job Service API to the Platform part of the SDK. Job results may be retrieved as stream output, file download, one big string, or an iterated list of lines, as with existing LiveQuery results support.
Job service has been run against PROD02 successfully. Unit tests have been added for all new code.  Coverage of new Jobs API is at 100%. No net loss of coverage in other portions of the SDK.  Test script run against PROD02 is as follows:
```
#!/usr/bin/env python
from cbc_sdk import CBCloudAPI
from cbc_sdk.audit_remediation import Run
api = …
```
=> CBAPI-3296: Live Query Async with Jobs Service

README.md
N/A
Added a note in the section of the `README.md` on generating the docs that, if the docs appear to generate incorrectly and the warnings indicate that Sphinx can't find the `cbc_sdk` module, setting the `PYTHONPATH` beforehand will resolve this. I stumbled into this particular trap myself, so I'm ensuring that I've documented the way out.
`README.md` update only, no code changes.
=> add a note about resolving "No module" errors when doing Sphinx doc build

docs/conf.py, src/cbc_sdk/platform/__init__.py, src/cbc_sdk/platform/devices.py, src/cbc_sdk/platform/models/device_facet.yaml, src/tests/uat/platform_devices_uat.py, src/tests/unit/fixtures/platform/mock_devices.py, src/tests/unit/platform/test_devicev6_api.py
https://jira.carbonblack.local/browse/CBAPI-3379
Added the facets() function to DeviceSearchQuery, which performs query faceting.  The facet values have an extra method of their own, query_devices(), which starts a search query for all devices matching that facet.
Unit tests have been updated and augmented to cover the new functionality. Coverage on that source file is at 94%. A UAT test for facets has also been added and proven to work against PROD02.
=> CBAPI-3379: Add Device Facet API to CBC SDK

src/cbc_sdk/base.py, src/cbc_sdk/enterprise_edr/threat_intelligence.py, src/tests/uat/watchlist_feed_uat.py, src/tests/unit/base/test_base_models.py, src/tests/unit/enterprise_edr/test_enterprise_edr_threatintel.py, src/tests/unit/fixtures/CBCSDKMock.py
https://jira.carbonblack.local/browse/CBAPI-3539
Replaces the v2 Watchlist APIs with v3 APIs, which includes ensuring that the org key is properly formatted into the URIs whenever necessary.
Unit tests have been adjusted to reflect the changes.  No net loss of coverage as a result.  Additionally, a UAT script has been added.
=> CBAPI-3539: Update SDK to use watchlist manager v3 instead of v2 APIs

docs/watchlists-feeds-reports.rst, src/cbc_sdk/enterprise_edr/threat_intelligence.py
https://jira.carbonblack.local/browse/CBAPI-3563, GitHub issue #271 
Changed documentation to reflect that `update()` should be used to update a `Report` that is part of a `Watchlist`.  Also documented that `save_watchlist()` should _not_ be used in this circumstance.
Documentation update only, no code changes.
=> CBAPI-3563: fix documenattion for save_watchlist() vs. update() on Report

docs/conf.py, src/cbc_sdk/platform/__init__.py, src/cbc_sdk/platform/alerts.py, src/cbc_sdk/platform/models/base_alert.yaml, src/tests/unit/platform/test_alertsv6_api.py
https://jira.carbonblack.local/browse/CBAPI-3577
Add support for container alerts (`ContainerRuntimeAlert` and associated query) to the CBC SDK.
**N.B.:** There are no changes to guides in this pull request because that is addressed in a subsequent ticket, CBAPI-3599, which will be worked immediately following this one.
Unit tests have been added to validate the new code.
**N.B.:** There is no UAT as part of this ticket because there are presently no UATs for alerts _at all._  This will be addressed in ticket CBAPI-3727, which has been scheduled as post-release 1.3.6 as per @kebringer-cb.
=> CBAPI-3577: Add containers alert type to SDK

src/cbc_sdk/platform/alerts.py
https://jira.carbonblack.local/browse/CBAPI-3766
Fixed the description of `BaseAlertSearchQuery.set_types` so that it mentions all valid alert types.
Doc fix only, no actual code change.
=> CBAPI-3766: fixed doc bug in BaseAlertSearchQuery.set_types

src/cbc_sdk/platform/devices.py, src/tests/unit/fixtures/platform/mock_devices.py, src/tests/unit/platform/test_devicev6_api.py
https://jira.carbonblack.local/browse/CBAPI-4055
Add the ability to facet devices on 3 new fields: `cloud_provider_account_id`, `auto_scaling_group_name`, and `virtual_private_cloud_id`.  This includes supporting `DeviceFacetValue.query_devices()` for each of the new field values.
Unit tests have been extended to cover all new code written; code coverage of the relevant file now stands at 95%. UAT did not require updates.
=> CBAPI-4055: Devices API - add 3 additional valid facet fields

src/cbc_sdk/workload/__init__.py, src/cbc_sdk/workload/vm_workloads_search.py, src/tests/uat/workloads_search_uat.py, src/tests/unit/base/test_queries.py, src/tests/unit/fixtures/workload/mock_search.py, src/tests/unit/workload/test_search.py, src/tests/unit/workload/test_sensor_lifecycle.py
https://jira.carbonblack.local/browse/CBAPI-4056
Update existing VM Workloads Search code in SDK to use v2 APIs. Also support new functionality, including AWS workloads support.
Unit tests have covered the workloads search code to 98%.   UAT script has been updated and run against vCenter workloads in a test environment.
=> CBAPI-4056: Upgrade VM Workloads Search to use v2 APIs

requirements.txt, src/cbc_sdk/platform/__init__.py, src/cbc_sdk/platform/models/policy_ruleconfig.yaml, src/cbc_sdk/platform/policies.py, src/cbc_sdk/rest_api.py, src/tests/unit/fixtures/platform/mock_policies.py, src/tests/unit/platform/test_policies.py
https://jira.carbonblack.local/browse/CBAPI-4375
Add basic rule config information to the `Policy` object.  This includes support for getting rule configurations, modifying them, adding them, deleting them, and incorporating them into a new `Policy` built with `PolicyBuilder.`
Some of this may overlap with the "core prevention" facilities; this is because "core prevention" rule configurations are among the simplest, and easy to use to verify operation.
Unit test coverage has been added for all new code in the module.  Coverage on `policies.py` stands at 97% overall.
=> CBAPI-4375: Add Basic Rule Config to Policy

src/cbc_sdk/connection.py, src/cbc_sdk/utils.py, src/tests/unit/test_base_api.py, src/tests/unit/test_utils.py
Removes code which manually handles query string parameters letting `requests` handle it (as described in [requests doc](https://docs.python-requests.org/en/latest/user/quickstart/?highlight=query%20params#passing-parameters-in-urls)).
Now the query_parameters param used in `get_object` and `get_raw_data` methods must be a dict or None.
When the param is a dict, it should not bring breaking changes. The only notable change is that requests does not add in query-string elements which values are `None`.
> Note that any dictionary key whose value is `None` will not be added to the URL’s query string.
- Run tests with py.test locally 
- manual fetch "Devices" by quering on `ad_group_id` and changing sort field/direction.
=> Cleanup code to use requests to parse query params

.readthedocs.yaml, docs/cbc_sdk.audit_remediation.rst, docs/cbc_sdk.cache.rst, docs/cbc_sdk.credential_providers.rst, docs/cbc_sdk.endpoint_standard.rst, docs/cbc_sdk.enterprise_edr.rst, docs/cbc_sdk.platform.rst, docs/cbc_sdk.rst, docs/cbc_sdk.workload.rst, docs/index.rst, docs/modules.rst, docs/requirements.txt, src/cbc_sdk/errors.py, src/cbc_sdk/platform/vulnerability_assessment.py
I modified the maxdepth of the SDK Documentation toctree to 4 as this enables the left nav to have the abiliity to see the file contents which makes identifiying and switching to the desired function easier
Additionally I think we want to swap  `:inherited-members:` for `:undoc-members:` as the undoc members seem to mostly be the properties which get pulled in from the swagger file and documented twice. The swagger properties are documented under the models Parameters section which should be enough. Plus any of the properties we do want users to see should have doc strings so there should be no undoc-members which we actually want documented
=> Adjust read the docs

docs/device-control.rst, src/tests/uat/device_control_uat.py
https://jira.carbonblack.local/browse/CBAPI-4876
Added documentation in ReadTheDocs for device export functions, and added code to UAT to test them.
(Also updated and "hardened" the UAT script a bit; it was a tad "brittle" in some aspects.)
UAT script has been run; log is in [device_control_uat.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/12233648/device_control_uat.log).  Doc file has been previewed for formatting errors.
=> CBAPI-4786: Add Documentation & UAT for External Device Export & Approval Export routes

src/cbc_sdk/platform/alerts.py, src/cbc_sdk/platform/legacy_alerts.py, src/tests/unit/platform/test_alertsv7_api.py
cbapi-4917 - add single value alert search criteria
Unit tests and manual e2e execution
=> Single value criteria

src/cbc_sdk/platform/alerts.py, src/tests/unit/platform/test_alertsv7_api.py
Found during testing.
Unit test and e2e execution locally.
=> New search method on Alert - set_remote_is_private

src/cbc_sdk/platform/alerts.py, src/tests/unit/platform/test_alertsv6_api.py, src/tests/unit/platform/test_alertsv7_api.py
Get_events got the assocatied enriched events. Enriched events are deprecated and were removed from the CBC console on Sept 26.  The API will remain available until July 31, 2024.4
CBAPI-4676
Added get_observations to Alert.
Removed get_events.  The original function now raises a FunctionalityDecommissioned exception.
locally e2e and unit tests added.
=> Added get_observations and removed get_events.

src/cbc_sdk/platform/legacy_alerts.py, src/tests/unit/platform/test_alertsv6_api.py, src/tests/unit/platform/test_alertsv7_api.py, src/tests/unit/platform/test_alertsv7_v6_compatibility.py, src/tests/unit/platform/test_platform_alerts_sdk150_breaking_changes.py
CBAPI-5046
In Alerts v7 API, many fields were renamed.  That means that legacy set_<fieldname> methods need to set the new name in the search criteria.  This PR updates the set methods, updates v6 test mocks to use new names and adds some 
new tests to validate the post request.
Validated with e2e scripts, and the post request checked in postman before using in the new mock requests.
=> CBAPI 5046 legacy alert set methods

src/cbc_sdk/rest_api.py
https://jira.carbonblack.local/browse/CBAPI-4931
Marked the `get_notifications()` and `notification_listener()` functions on `CBCloudAPI` as deprecated, and did a small "beauty pass" through the docstrings in that file.
Primarily doc changes, no substantive code changes. Unit tests still pass.
=> CBAPI-4931: Mark CBCloudAPI.get_notifications() as deprecated

src/cbc_sdk/platform/alerts.py
In Alerts v7 API, several alert types can be associated with a process, not only Watchlist.
If the alert does not have a process guid, the process request will fail.
=> Move get process to base Alert instead of Watchlist

examples/platform/alerts_bulk_export.py, src/cbc_sdk/platform/alerts.py, src/tests/unit/platform/test_alertsv6_api.py, src/tests/unit/platform/test_alertsv7_api.py
Updated time validation - backend_timestamp is not valid "criteria" Removed some tests - need to revisit, replacements that expect an exception are likely needed to replace them
the period searched by backend_timestamp is set at the top level time_range element of the request.
Previously, if backend_timestamp was set in the criteria section, it was silently ignored or gave very hard to calculate results.  In mid-october the backend updated to return an error if backend_timestamp was in criteria.
This change updates the SDK to be more strict in line with that change.
- set_time_range(start/end/range) --> sets time_range{} element. Correct v7 use of the method
- set_time_range("create_time",...) --> sets time_range{} element. …
=> Alerts - updated time validation and added bulk export example script

src/cbc_sdk/platform/processes.py, src/tests/unit/fixtures/platform/mock_process.py, src/tests/unit/platform/test_platform_process.py
https://jira.carbonblack.local/browse/CBAPI-5078
Add `deobfuscate_cmdline()` helper function to `Process`, which calls the Script Deobfuscation API.
New unit test has been added for the function, and an additional one added to help bring up code coverage in the `processes.py` file.  Code coverage is at 93%, mainly because of other bits of process support that aren't easily testable.
=> CBAPI-5078: Add deobfuscate_cmdline() to Process

src/cbc_sdk/platform/observations.py, src/tests/unit/fixtures/platform/mock_observations.py, src/tests/unit/platform/test_observations.py
https://jira.carbonblack.local/browse/CBAPI-5079
Added the `deobfuscate_cmdline()` helper function to the `Observation` class.
Unit test added for new function; coverage in `observations.py` is 96%.  Run against an example `Observation` on `prod02`.
=> CBAPI-5079: Add deobfuscate_cmdline() to Observation

src/cbc_sdk/platform/alerts.py, src/tests/unit/fixtures/platform/mock_alerts_v7.py, src/tests/unit/platform/test_alertsv7_api.py
https://jira.carbonblack.local/browse/CBAPI-5080
Add the `deobfuscate_cmdline()` helper function to `Alert`.
Unit test written for new function; test coverage in `alerts.py` is 94% (new function did not add to number of uncovered lines). Deobfuscation run against a large number of alerts on `prod02`.
=> CBAPI-5080: Add deobfuscate_cmdline() to Alert

src/cbc_sdk/platform/asset_groups.py, src/cbc_sdk/platform/models/asset_group.yaml, src/tests/unit/fixtures/platform/mock_asset_groups.py, src/tests/unit/platform/test_asset_groups.py
https://jira.carbonblack.local/browse/CBAPI-4251
Added dynamic criteria support (the `query` attribute) to the asset groups.
Unit tests have been modified to use the `query` attribute throughout, especially when testing `create_group()`. Coverage for the file stands at 97%.
=> CBAPI-4251: Add Dynamic Criteria support to Asset Groups

src/cbc_sdk/base.py, src/cbc_sdk/platform/asset_groups.py, src/tests/unit/fixtures/platform/mock_asset_groups.py, src/tests/unit/platform/test_asset_groups.py
https://jira.carbonblack.local/browse/CBAPI-5148
Bugfixes and enhancements to Asset Groups Search as follows:
* All URLs have been modified to contain `v1` instead of `v1beta` as a version indicator.
* In queries, the `start` parameter defaults to 0 instead of 1.
* `criteria` and `query` are elided from search parameters if they're empty.
* All "discrete" criteria functions have been removed, `add_criteria()` will be used to manage criteria on `AssetGroupQuery` exclusively. Documentation has been added to `AssetGroupQuery` class docstring showing which criteria are valid, including the new `group_id` criteria.
* A `set_rows()` method has been added allowing the default number of rows in a batch to be set (defaults to 100).
No …
=> CBAPI-5148: Asset Groups - Search (bugfix / update)

src/cbc_sdk/platform/asset_groups.py, src/tests/unit/fixtures/platform/mock_asset_groups.py, src/tests/unit/platform/test_asset_groups.py
https://jira.carbonblack.local/browse/CBAPI-4254
Added `get_all_groups()` (class method) and `get_statistics()` methods to `AssetGroup`.
Unit tests have been added for the two new methods; overall coverage in `asset_groups.py` stands at 98%.  Log file of run of the new functions against DEV01 is here: [misc_functions_asset_groups.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/13719162/misc_functions_asset_groups.log)
=> CBAPI-4254: Asset Group Support in CBC SDK p4 - Additional Member Functions

src/cbc_sdk/platform/asset_groups.py
https://jira.carbonblack.local/browse/CBAPI-5208
Changed the behavior of `create_group()` function so that all parameters except `name` for the new group are optional.  Documentation also changed accordingly.
(The request for modifiability as specified in the original JIRA ticket was mostly supported already. This detail needed to be fixed up, through.)
Existing tests cover this new case adequately; test coverage of `asset_groups.py` is still 98%. Log of a group being created without a description and then having one added afterwards is here: [description-null.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/13847381/description-null.log)
=> CBAPI-5208: Asset Groups - modify group

src/cbc_sdk/platform/policies.py, src/tests/unit/fixtures/platform/mock_policies.py, src/tests/unit/fixtures/platform/mock_policy_ruleconfigs.py, src/tests/unit/platform/test_policies.py
https://jira.carbonblack.local/browse/CBAPI-5116
Added helper methods to `Policy`, `set_xdr_collection` and `set_auth_event_collection`, that allow XDR data collection and auth event data collection to be quickly turned on and off for a policy.  This would allow someone to do it easily for _all_ policies in an organization by using a simple for loop.
Unit tests have been written to cover all the new code. Coverage for `policies.py` stands at 96%.  Log of run against PROD02 is here: [set_policy_shortcuts.log](https://github.com/carbonblack/carbon-black-cloud-sdk-python/files/14028928/set_policy_shortcuts.log)
=> CBAPI-5116: Helper Method - Set XDR and Auth Event Data Collection policy on/off

docs/authentication.rst, docs/searching.rst, src/cbc_sdk/base.py, src/cbc_sdk/connection.py, src/cbc_sdk/credential_providers/registry_credential_provider.py, src/cbc_sdk/credentials.py, src/cbc_sdk/endpoint_standard/base.py, src/cbc_sdk/enterprise_edr/auth_events.py, src/cbc_sdk/platform/observations.py, src/cbc_sdk/platform/processes.py, src/cbc_sdk/rest_api.py, src/tests/unit/credential_providers/test_aws_secrets_manager.py, src/tests/unit/credential_providers/test_registry.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events_facet.py, src/tests/unit/enterprise_edr/test_auth_events.py, src/tests/unit/platform/test_observations.py, src/tests/unit/platform/test_platform_process.py, src/tests/unit/platform/test_platform_query.py, src/tests/unit/test_credentials.py
https://jira.carbonblack.local/browse/CBAPI-5134
Added behavior that all search queries that have timeout values respect the configured default timeout value, which defaults to 300000 milliseconds (5 minutes) and is configured as part of the credentials.
Customers that have been submitting extra-long searches and having them hang will now start seeing `TimeoutError` being thrown. This has always been a documented response from those searches, though, so they will get better feedback on searches that are too long. In that sense, it isn't really a "breaking" change, but it is a difference in behavior.
Test coverage has been verified for anything that references timeouts. Overall test coverage should have improved.
=> CBAPI-5134: Set a default timeout on waiting for search jobs to complete

src/cbc_sdk/platform/devices.py
#397
Add deployment_type field to the facets for DeviceSearchQuery. This will help to get numbers for the different deployment types easily.
Not at the CBC SDK level, but yes at API backend level. Since, as you can see below, the response of the API is HTTP 400.
With this small code snippet:
```
from cbc_sdk import CBCloudAPI
from cbc_sdk.platform import Device, DeviceFacet
import logging
import requests
cb_api = CBCloudAPI(profile='devices')
try:
device_facets = cb_api.select(Device).set_status(["ALL"]).facets(['deployment_type'])
print(device_facets)
except Exception as er:
logging.error(er)
```
Response from backend:
```
ERROR:root:Received error code 400 from API: {"error_code":"MALFORMED_JSON","message":"Malformed JSON …
```
=> Add deployment_type as part of DeviceSearchQuery facets

src/cbc_sdk/platform/devices.py
https://jira.carbonblack.local/browse/CBAPI-5221
Update the documentation and behavior of `DeviceFacet` and related code to ensure proper support for all new facetable fields.
Unit tests pass on new code in `query_devices()` method; `devices.py` coverage now sits at 95%.
=> CBAPI-5221: Update Device Facet to support new fields

docs/devices.rst, docs/guides.rst
=> CBAPI-3712: guide for Device Actions

src/cbc_sdk/audit_remediation/base.py, src/cbc_sdk/base.py, src/cbc_sdk/platform/alerts.py, src/cbc_sdk/platform/devices.py, src/cbc_sdk/platform/events.py, src/cbc_sdk/platform/processes.py, src/cbc_sdk/platform/vulnerability_assessment.py, src/tests/unit/platform/test_platform_events.py, src/tests/unit/platform/test_vulnerability_assessment.py
https://jira.carbonblack.local/browse/CBAPI-5303
1. The arguments to `_perform_query` have been normalized across the entire SDK, so the shortcuts in `IterableQueryMixin` will work correctly in all circumstances.
2. In `IterableQueryMixin`, `first()` has been reimplemented so it will send a query with a `rows` parameter of 1.
Note: The arguments to `_perform_query` have been normalized across the entire code, but SDK users shouldn't be using that method directly anyway.
All unit tests pass with this fix. The code has been offered to Kyle for testing to see if it meets his needs.  (He reports that it does.)
=> CBAPI-5303: Fix SDK bugs as reported by Kyle at Aplura

src/cbc_sdk/platform/audit.py, src/tests/unit/fixtures/platform/mock_audit.py, src/tests/unit/platform/test_audit.py
https://jira.carbonblack.local/browse/CBAPI-5259
Added function `get_queued_auditlogs()` that does what `get_auditlogs()` did, only in terms of actual new `AuditLog` objects.  Older `get_auditlogs()` function has been marked as deprecated.
Unit test covers the new function; test coverage for `audit.py` now stands at 97%.
=> CBAPI-5259: Reimplement AuditLog.get_auditlogs in terms of new API

docs/audit-log.rst
https://jira.carbonblack.local/browse/CBAPI-5261
Rewrite Audit Log guide page to describe the new APIs.
Docs built and viewed locally to ensure guide page formatting is OK.
=> CBAPI-5261: Guide page for Audit Log functionality

requirements.txt, setup.py, src/cbc_sdk/platform/alerts.py, src/cbc_sdk/platform/audit.py
#520 
This is an implementation of a conditional `backports._datetime_fromisoformat` depedency based on the python version. The `MonkeyPatch `method is the default usage recommended on https://github.com/movermeyer/backports.datetime_fromisoformat
Should be transparent to user before and after 3.11, as `backports._datetime_fromisoformat` backports the `datetime.fromisoformat` functionality identically. Would simplify installation process by removing the need of a C compiler on the machine for engineers using python 3.11 or 3.12.
Only minimal tests done to ensure implementation worked. May need further evaluation.
=> Fix backport datetime fromisoformat dependency

src/cbc_sdk/live_response_api.py, src/tests/unit/fixtures/live_response/mock_command.py, src/tests/unit/test_live_response_api.py
DSER-50836 related to CRE-17921
Fixed bug when command_id=0 then get_raw_file() was always returning NONE
Test cases updated. 
Tested with standalone script
=> DSER-50836: CB Defense / EEDR: Live Response API, large file transfers (downloads) are failing with 201 Status Code

src/cbc_sdk/base.py, src/cbc_sdk/endpoint_standard/base.py, src/cbc_sdk/enterprise_edr/auth_events.py, src/cbc_sdk/platform/observations.py, src/cbc_sdk/platform/processes.py, src/tests/uat/enriched_events_uat.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events.py, src/tests/unit/endpoint_standard/test_endpoint_standard_enriched_events_facet.py, src/tests/unit/enterprise_edr/test_auth_events.py, src/tests/unit/fixtures/endpoint_standard/mock_enriched_events.py, src/tests/unit/fixtures/endpoint_standard/mock_enriched_events_facet.py, src/tests/unit/fixtures/enterprise_edr/mock_auth_events.py, src/tests/unit/fixtures/platform/mock_observations.py, src/tests/unit/fixtures/platform/mock_process.py, src/tests/unit/platform/test_alertsv7_api.py, src/tests/unit/platform/test_observations.py, src/tests/unit/platform/test_platform_process.py
N/A
This PR enforces timeouts for search jobs with zero contacted searchers. I encountered an infinite loop when calling `list(cb.select(Process).where(search_string).timeout(15000))` in a new org that didn't yet have data.
I verified `list(cb.select(Process).where(search_string).timeout(15000))` now times out after 15 seconds in an org without data.
=> Enforced timeouts for search jobs with zero contacted searchers
